scrape_configs:
  - job_name: 'SocialMediaMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['social-media:13500']
        labels:
          application: 'Social Media'